language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wendel/docker-react -f Dockerfile.dev .

script: 
  - docker run -t wendel/docker-react npm run test -- --coverage